apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose_files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
          image: ui
          livenessProbe:
            exec:
              command:
                - curl -s -f http://localhost:8080/actuator/health || exit 1
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          name: ui
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
          securityContext:
            capabilities:
              drop:
                - ALL
      hostname: ui
      restartPolicy: Always
