apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: checkout
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose_files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: checkout
    spec:
      containers:
        - env:
            - name: RETAIL_CHECKOUT_PERSISTENCE_PROVIDER
              value: redis
            - name: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
              value: redis://checkout-redis:6379
          image: checkout
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8080/health || exit 1
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 10
          name: checkout
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: checkout-tmpfs0
      hostname: checkout
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: checkout-tmpfs0
