apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cart
  name: cart
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: cart
