apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose_files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cart
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: key
            - name: AWS_SECRET_ACCESS_KEY
              value: dummy
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
              value: "true"
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT
              value: http://carts-db:8000
            - name: RETAIL_CART_PERSISTENCE_PROVIDER
              value: dynamodb
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
          image: cart
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8080/actuator/health || exit 1
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          name: cart
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: cart-tmpfs0
      hostname: carts
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: cart-tmpfs0
