apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: carts-db
  name: carts-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: carts-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose_files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: carts-db
    spec:
      containers:
        - image: amazon/dynamodb-local:1.20.0
          livenessProbe:
            exec:
              command:
                - exit 0
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 15
          name: carts-db
          ports:
            - containerPort: 8000
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: carts-db-tmpfs0
      hostname: carts-db
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: carts-db-tmpfs0
