apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_files
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: orders-db
  name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose_files
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: orders-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_PASSWORD
              value: retailstore
            - name: POSTGRES_USER
              value: orders_user
            - name: reschedule
              value: on-node-failure
          image: postgres:16.1
          livenessProbe:
            exec:
              command:
                - pg_isready -d orders -U orders_user
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: orders-db
          ports:
            - containerPort: 5432
              protocol: TCP
      hostname: orders-db
      restartPolicy: Always
