[project]
name = "pulumi-start-aws"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=7.0.0,<8.0.0",
    "pulumi-awsx>=3.0.1",
    "pulumi-eks>=4.0.1",
    "pulumi-kubernetes>=4.23.0",
    "pulumi-kubernetes-ingress-nginx>=0.1.3",
]
