name: Deploy to EKS

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  pulumi:
      name: Pulumi Apply
      runs-on: ubuntu-latest
      env:
        working_directory: pulumi
        AWS_REGION: ${{ secrets.AWS_REGION }}
      defaults:
        run:
          shell: bash
          working-directory: $env.working_directory

      steps:   
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Verify AWS CLI access
          run: aws sts get-caller-identity

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install uv (for pip's replacement, yeahhhh)
          uses: astral-sh/setup-uv@v6
          with:
            version: "0.9.5"

        - name: Install pulumi python deps 
          run: uv sync
          
        - uses: pulumi/actions@v6
          with:
            command: up
            stack-name: dev
            comment-on-pr: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
            work-dir: $env.working_directory
            upsert: true
          env:
            PULUMI_BACKEND_URL: file://.