name: Deploy to EKS

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  pulumi:
      name: Pulumi Apply
      runs-on: ubuntu-latest
      env:
        pulumi_dir: pulumi
        AWS_REGION: ${{ secrets.AWS_REGION }}
        CERT_MANAGER_EMAIL: ${{ secrets.CERT_MANAGER_EMAIL }}

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Verify AWS CLI access
          run: aws sts get-caller-identity
          
        - name: Install Pulumi CLI
          uses: pulumi/actions-install-pulumi-cli@v3