name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  terraform:
      name: Terraform Apply
      runs-on: ubuntu-latest
      needs: [build-and-push]
      env:
        terraform_dir: terraform
        AWS_REGION: ${{ vars.AWS_REGION }}
        CERT_MANAGER_EMAIL: ${{ vars.CERT_MANAGER_EMAIL }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
        
        - name: Verify AWS CLI access
          run: aws sts get-caller-identity
        
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Create tfvars file
          run: |
            cd $terraform_dir
            echo "region = \"$AWS_REGION\"" > terraform.tfvars
            echo "certmanager_email = \"$CERT_MANAGER_EMAIL\"" >> terraform.tfvars
        
        - name: Terraform Init
          run: |
            cd $terraform_dir
            terraform init
        
        - name: Terraform Apply
        run: |
          cd $terraform_dir
          terraform apply -auto-approve
